package paquete.clases;



/**
 * EmpDetailsView generated by hbm2java
 */
public class EmpDetailsView implements java.io.Serializable {

	private EmpDetailsViewId id;

	public EmpDetailsView() {
	}

	public EmpDetailsView(EmpDetailsViewId id) {
		this.id = id;
	}

	public EmpDetailsViewId getId() {
		return this.id;
	}

	public void setId(EmpDetailsViewId id) {
		this.id = id;
	}

}
